INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Karol', 'Karol', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'dogier2509@gmail.com', 'ADMIN', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Jan', 'Kowalski', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'dasdas@gmail.com', 'DESIGNER', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Andrzej', 'Operator', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'dasdas1@gmail.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Jane', 'Smith', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'jane.smith@example.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Alice', 'Johnson', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'alice.johnson@example.com', 'DESIGNER', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Eva', 'Anderson', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'eva.anderson@example.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Charlie', 'Miller', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'charlie.miller@example.com', 'DESIGNER', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('David', 'Harris', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'david.harris@example.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Sophie', 'Martin', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'sophie.martin@example.com', 'DESIGNER', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Tom', 'Johnson', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'tom.johnson@example.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Emma', 'White', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'emma.white@example.com', 'DESIGNER', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Oliver', 'Lee', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'oliver.lee@example.com', 'OPERATOR', true);
INSERT INTO user (firstName, lastName, password, email, role, isEnabled) VALUES ('Mia', 'Clark', '$2a$10$QiiOVSnnNeYq.qT.rdGthu6JL1klNn6J0hs63WMXzb12jNOk2.2xi', 'mia.clark@example.com', 'DESIGNER', true);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Design Logo', 'Logo for new brand', 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Website Update', 'Update the front page', 2, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Mobile App UI', 'Design UI for Android app', 1, 'CLOSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Marketing Graphics', 'Create graphics for campaign', 2, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Product Design', 'Design new kitchen product', 1, 'ARCHIVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Email Templates', 'Create templates for marketing', 2, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Brand Strategy', 'Develop a brand strategy', 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Social Media Ads', 'Design ads for social media', 2, 'CLOSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Packaging Design', 'Design packaging for new product', 1, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO task (taskName, description, assigned_designer_id, taskStatus, createdAt, editedAt) VALUES ('Infographic Creation', 'Create informative infographics', 2, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 1, 1);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 1, 2);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 2, 3);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 2, 4);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 1, 5);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 1, 6);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 2, 7);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 2, 8);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 1, 9);
INSERT INTO working_time (createdAt, workStarted, workFinished, currentWorkingTime, overallWorkingTime, isWorking, user_id, task_id) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 0, 0, FALSE, 2, 10);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Good job!', 8, TRUE, 1);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Could be better.', 5, TRUE, 2);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Excellent work!', 9, TRUE, 3);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Satisfactory.', 6, TRUE, 4);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Well done!', 7, TRUE, 5);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Needs improvement.', 4, TRUE, 6);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Outstanding performance!', 10, TRUE, 7);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Average work.', 5, TRUE, 8);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Impressive!', 9, TRUE, 9);
INSERT INTO task_feedback (feedback, difficulty, isSet, task_id) VALUES ('Room for improvement.', 6, TRUE, 10);
